name: calculator
description: "Flutter Calculator App "

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1 # Requires Dart SDK version x.x.x or higher


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1 
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/


